#!/usr/bin/env node
// Generate the extension contract from the Rust method catalog. --check never writes source files.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import standalone from "ajv/dist/standalone/index.js";
import { build } from "esbuild";
import { compile } from "json-schema-to-typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const destination = join(root, "apps/extension/src/transport/generated");
const banner = "// Generated by scripts/protocol.mjs from bsk-protocol. Do not edit.\n";
const args = new Set(process.argv.slice(2));
if ([...args].some((arg) => !["--check", "--json"].includes(arg))) {
  throw new Error("Usage: node scripts/protocol.mjs [--check] [--json]");
}
function runExporter(binary, extraArgs = []) {
  const exported = spawnSync(
    "cargo",
    [
      "run",
      "--quiet",
      "--locked",
      "--target-dir",
      join(root, "target/protocol"),
      "-p",
      "bsk-protocol",
      "--bin",
      binary,
      ...extraArgs,
    ],
    { cwd: root, encoding: "utf8", maxBuffer: 32 * 1024 * 1024, timeout: 300_000 },
  );
  if (exported.status !== 0) throw new Error(exported.error?.message ?? exported.stderr);
  return exported.stdout;
}
const catalog = JSON.parse(runExporter("export-protocol"));
// Export through the same Rust entry point as cli:build. Even --check writes
// only into this temporary directory before comparing checked-in schemas.
const temporarySchemas = mkdtempSync(join(tmpdir(), "bsk-protocol-"));
let schemas;
try {
  runExporter("dump-schema", ["--", "--out-dir", temporarySchemas]);
  schemas = new Map(
    readdirSync(temporarySchemas)
      .sort()
      .map((name) => [name, readFileSync(join(temporarySchemas, name), "utf8")]),
  );
} finally {
  rmSync(temporarySchemas, { recursive: true, force: true });
}
if (catalog.format_version !== 1 || !catalog.methods.length)
  throw new Error("Invalid protocol catalog");
const definitions = catalog.schema.definitions;
const names = Object.keys(definitions).sort();
const methods = catalog.methods.filter((method) => method.owner === "extension");
if (
  !methods.length ||
  new Set(catalog.methods.map((method) => method.method)).size !== catalog.methods.length
) {
  throw new Error("Empty or duplicate method catalog");
}
for (const method of catalog.methods) {
  for (const name of [method.params, method.result]) {
    if (!(name in definitions)) throw new Error(`Missing contract ${method.method}: ${name}`);
  }
}

// The wire accepts legacy null for optional typed fields. Internally these are
// represented by omission. Arbitrary JSON (including null), required nullable
// values, and dictionary values retain their original meaning.
function permitsNull(schema) {
  if (!schema || typeof schema !== "object") return false;
  return (
    schema.type === "null" ||
    (Array.isArray(schema.type) && schema.type.includes("null")) ||
    (schema.anyOf ?? schema.oneOf ?? []).some((part) => part.type === "null")
  );
}
function canonical(schema) {
  if (!schema || typeof schema !== "object") return schema;
  const result = structuredClone(schema);
  const visit = (node) => {
    if (!node || typeof node !== "object") return;
    if (node.properties) {
      const required = new Set(node.required ?? []);
      for (const [key, property] of Object.entries(node.properties)) {
        if (!required.has(key) && permitsNull(property)) {
          if (Array.isArray(property.type)) {
            property.type = property.type.filter((type) => type !== "null");
            if (property.type.length === 1) property.type = property.type[0];
          }
          for (const union of ["anyOf", "oneOf"]) {
            if (property[union])
              property[union] = property[union].filter((part) => part.type !== "null");
          }
        }
      }
    }
    for (const value of Object.values(node)) {
      if (Array.isArray(value)) value.forEach(visit);
      else if (value && typeof value === "object") visit(value);
    }
  };
  visit(result);
  return result;
}

const normalized = canonical(catalog.schema);
const outputSchema = canonical(catalog.output_schema);
// Conditional schema constraints remain in runtime validators. TypeScript can
// represent the union of their outcomes, but cannot express arbitrary predicates.
function typeProjection(schema) {
  if (!schema || typeof schema !== "object") return schema;
  if (Array.isArray(schema)) return schema.map(typeProjection);
  const result = Object.fromEntries(
    Object.entries(schema).map(([key, value]) => [key, typeProjection(value)]),
  );
  if (result.properties) {
    result.properties = Object.fromEntries(
      Object.entries(result.properties).filter(
        ([, value]) => value !== false && !(value?.not && !value.type && !value.$ref),
      ),
    );
    // Wire readers may ignore extension fields. They are not fields produced by our tools.
    result.additionalProperties ??= false;
  }
  if (result.if) {
    const alternatives = { anyOf: [result.then ?? {}, result.else ?? {}] };
    delete result.if;
    delete result.then;
    delete result.else;
    result.allOf = [...(result.allOf ?? []), alternatives];
  }
  return result;
}
async function compileTypes(schema) {
  const projected = typeProjection(schema);
  const typeSchema = {
    ...projected,
    definitions: Object.fromEntries(
      Object.entries(projected.definitions).map(([name, schema]) => [
        name,
        schema === true ? {} : schema === false ? { not: {}, tsType: "never" } : schema,
      ]),
    ),
    title: "ProtocolTypes",
    type: "object",
    properties: Object.fromEntries(names.map((name) => [name, { $ref: `#/definitions/${name}` }])),
    required: names,
    additionalProperties: false,
  };
  return compile(typeSchema, "ProtocolTypes", {
    bannerComment: banner.trim(),
    additionalProperties: false,
    unreachableDefinitions: true,
    unknownAny: true,
    ignoreMinAndMaxItems: true,
    format: true,
    style: { printWidth: 100, tabWidth: 2 },
  });
}
const inputTypes = await compileTypes(normalized);
const outputTypes = await compileTypes(outputSchema);
const paramNames = new Set(catalog.methods.map((method) => method.params));
const types =
  banner +
  names
    .map((name) => `export type { ${name} } from './${paramNames.has(name) ? "input" : "output"}';`)
    .join("\n") +
  "\n";

const wireId = "urn:bsk:wire";
const canonicalId = "urn:bsk:canonical";
const ajv = new Ajv({
  strict: false,
  validateFormats: false,
  inlineRefs: false,
  code: { source: true, esm: true, lines: true },
});
ajv.addSchema({ ...catalog.schema, $id: wireId });
ajv.addSchema({ ...normalized, $id: canonicalId });
const outputId = "urn:bsk:output";
ajv.addSchema({ ...outputSchema, $id: outputId });
const validators = {};
const inputRoots = [
  ...new Set([...methods.map((method) => method.params), "CancelParams", "HandshakeResponse"]),
].sort();
for (const name of inputRoots) {
  validators[`wire_${name}`] = `${wireId}#/definitions/${name}`;
  validators[`canonical_${name}`] = `${canonicalId}#/definitions/${name}`;
}
for (const name of [...new Set([...methods.map((method) => method.result), "RpcError"])].sort()) {
  validators[`canonical_${name}`] = `${outputId}#/definitions/${name}`;
}

// Emit ordinary functions, including branch selection against the wire schema.
// This keeps normalization immutable and preserves tagged unions and dictionaries.
const normalizers = [];
let nextNormalizer = 0;
const normalizedDefinitions = new Set();
function normalizeDefinition(name) {
  if (normalizedDefinitions.has(name)) return;
  normalizedDefinitions.add(name);
  normalizer(definitions[name], `#/definitions/${name}`, `normalize_${name}`);
}
function normalizer(schema, pointer, name = `normalize_${nextNormalizer++}`) {
  const lines = [];
  if (!schema || typeof schema !== "object") {
    normalizers.push(`function ${name}(value: unknown): unknown { return value; }`);
    return name;
  }
  const call = (child, path, expression) => `${normalizer(child, path)}(${expression})`;
  if (schema.$ref) {
    const reference = schema.$ref.split("/").at(-1);
    normalizeDefinition(reference);
    lines.push(`return normalize_${reference}(value);`);
  } else {
    lines.push("let result = value;");
    if (schema.properties || schema.additionalProperties) {
      lines.push(
        "if (typeof result === 'object' && result !== null && !Array.isArray(result)) {",
        "const object: Record<string, unknown> = { ...result };",
      );
      const required = new Set(schema.required ?? []);
      for (const [key, child] of Object.entries(schema.properties ?? {})) {
        const field = `object[${JSON.stringify(key)}]`;
        const path = `${pointer}/properties/${key.replaceAll("~", "~0").replaceAll("/", "~1")}`;
        if (!required.has(key) && permitsNull(child))
          lines.push(`if (${field} === null) delete ${field};`);
        lines.push(
          `if (Object.hasOwn(object, ${JSON.stringify(key)})) ${field} = ${call(child, path, field)};`,
        );
      }
      if (typeof schema.additionalProperties === "object") {
        const child = normalizer(schema.additionalProperties, `${pointer}/additionalProperties`);
        lines.push(
          `for (const key of Object.keys(object)) { if (!new Set<string>(${JSON.stringify(Object.keys(schema.properties ?? {}))}).has(key)) object[key] = ${child}(object[key]); }`,
        );
      }
      lines.push("result = object;", "}");
    }
    if (schema.items && !Array.isArray(schema.items)) {
      const child = normalizer(schema.items, `${pointer}/items`);
      lines.push(`if (Array.isArray(result)) result = result.map(${child});`);
    }
    for (const [index, child] of (schema.allOf ?? []).entries()) {
      lines.push(`result = ${call(child, `${pointer}/allOf/${index}`, "result")};`);
    }
    for (const union of ["anyOf", "oneOf"]) {
      if (!schema[union]) continue;
      schema[union].forEach((child, index) => {
        const path = `${pointer}/${union}/${index}`;
        const validator = `branch_${Object.keys(validators).length}`;
        validators[validator] = `${wireId}${path}`;
        lines.push(
          `${index ? "else " : ""}if (validators.${validator}(value)) result = ${call(child, path, "result")};`,
        );
      });
    }
    if (schema.if) {
      const validator = `branch_${Object.keys(validators).length}`;
      validators[validator] = `${wireId}${pointer}/if`;
      const yes = schema.then ? call(schema.then, `${pointer}/then`, "result") : "result";
      const no = schema.else ? call(schema.else, `${pointer}/else`, "result") : "result";
      lines.push(`result = validators.${validator}(value) ? ${yes} : ${no};`);
    }
    lines.push("return result;");
  }
  normalizers.push(`function ${name}(value: unknown): unknown {\n${lines.join("\n")}\n}`);
  return name;
}
for (const name of inputRoots) normalizeDefinition(name);
const validatorSource = standalone(ajv, validators);
const bundled = await build({
  stdin: { contents: validatorSource, resolveDir: root, sourcefile: "protocol-validators.js" },
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
  legalComments: "none",
});
const validationTypes =
  banner +
  "export interface ValidationIssue { instancePath: string; message?: string; keyword: string; }\n" +
  "export interface Validator { (value: unknown): boolean; errors?: ValidationIssue[] | null; }\n" +
  Object.keys(validators)
    .map((name) => `export const ${name}: Validator;`)
    .join("\n") +
  "\n";
const normalizationSource =
  banner +
  "import * as validators from './validators.js';\n" +
  normalizers.join("\n\n") +
  `\nexport const normalizers = { ${inputRoots.map((name) => `${name}: normalize_${name}`).join(", ")} } as const;\n`;
const methodSource =
  banner +
  "import type * as Types from './types';\n" +
  `export const PROTOCOL_VERSION = ${JSON.stringify(catalog.protocol_version)};\n` +
  `export const MIN_COMPATIBLE_PROTOCOL = ${JSON.stringify(catalog.min_compatible_protocol)};\n` +
  Object.entries(catalog.constants)
    .map(([name, value]) => `export const ${name} = ${JSON.stringify(value)};\n`)
    .join("") +
  `export const debugActions = ${JSON.stringify(catalog.debug_actions, null, 2)} as const;\n` +
  `export const methods = ${JSON.stringify(catalog.methods, null, 2)} as const;\n` +
  `export interface ToolMap {\n${methods.map((method) => `  ${JSON.stringify(method.method)}: { params: Types.${method.params}; result: Types.${method.result} };`).join("\n")}\n}\n` +
  "export type ExtensionToolMethod = keyof ToolMap;\n" +
  "export type ParamsOf<M extends ExtensionToolMethod> = ToolMap[M]['params'];\n" +
  "export type ResultOf<M extends ExtensionToolMethod> = ToolMap[M]['result'];\n";
const fingerprint = createHash("sha256").update(JSON.stringify(catalog)).digest("hex");
const outputs = new Map([
  ["types.ts", types],
  ["input.ts", inputTypes],
  ["output.ts", outputTypes],
  ["methods.ts", methodSource],
  ["validators.js", banner + bundled.outputFiles[0].text],
  ["validators.d.ts", validationTypes],
  ["normalizers.ts", normalizationSource],
  [
    "manifest.json",
    JSON.stringify(
      {
        source: "bsk-protocol",
        fingerprint,
        methods: methods.map((m) => m.method),
        contracts: names,
      },
      null,
      2,
    ) + "\n",
  ],
]);
const changed = [];
for (const [directory, files, label] of [
  [destination, outputs, ""],
  [join(root, "crates/bsk-protocol/schema"), schemas, "schema/"],
]) {
  let unexpected = [];
  try {
    unexpected = readdirSync(directory).filter((name) => !files.has(name));
  } catch {}
  if (unexpected.length)
    throw new Error(
      `Unexpected generated files: ${unexpected.map((name) => label + name).join(", ")}`,
    );
  for (const [name, source] of files) {
    let existing;
    try {
      existing = readFileSync(join(directory, name), "utf8");
    } catch {}
    if (existing !== source) changed.push(label + name);
    if (!args.has("--check")) {
      mkdirSync(directory, { recursive: true });
      writeFileSync(join(directory, name), source);
    }
  }
}
const report = {
  methods: methods.length,
  contracts: names.length,
  schemas: schemas.size,
  fingerprint,
  stale: changed,
};
console.log(
  args.has("--json")
    ? JSON.stringify(report, null, 2)
    : `${args.has("--check") ? "Checked" : "Generated"} ${methods.length} extension methods, ${names.length} contracts and ${schemas.size} standalone schemas.${args.has("--check") && changed.length ? ` Stale: ${changed.join(", ")}. Run pnpm protocol:generate.` : ""}`,
);
if (args.has("--check") && changed.length) process.exitCode = 1;
